  services:

    mysql:
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: lake
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      ports:
        - "33061:3306"
      volumes:
        - ./dashboard_testing/docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        - ./dashboard_testing/docker/mysql-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh:ro  # Custom startup script

    tests:
      build:
        context: .
        dockerfile: dashboard_testing/docker/Dockerfile

      image: polarisadvisor/dashboard-testing:latest
      depends_on:
        - mysql
      environment:
        DATABASE_URL: mysql+pymysql://test:test@mysql:3306/lake
        PYTHONPATH: /app/dashboard_testing

      volumes:
        - .:/app  # Mount the entire project directory
      working_dir: /app
      entrypoint: [ "/bin/bash", "dashboard_testing/docker/entrypoint.sh" ]



