{
 "title": "Where is time spent on the path to production?",
 "description": "Commit to Deploy Flow Time",
 "tags": [
  "Perspective: The Path to Production",
  "Unit of Work: Pull Requests"
 ],
 "time": { "from": "now-180d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "How long does it take for changes on a branch to reach production?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lead time for changes (Merged PRs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 1, "y": 1 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below\n\t\tcoalesce(prm.pr_cycle_time/3600,0) as cycle_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL - $interval(date(pr_merged_date))+1 DAY) as time,\n  avg(cycle_time) as 'PR Lead Time for Changes (d)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Where is time spent in this process? ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "From initial commit to PR raised",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 1, "y": 9 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no coding_time to make sure cycle_time equals the sum of the four sub-metrics\n\t\tcoalesce(prm.pr_coding_time/1440,0) as coding_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(coding_time) as 'Coding Time(days)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "From PR raised to PR Merged",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 8, "y": 9 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    prm.pr_created_date,\n    prm.pr_merged_date \n    \n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL - $interval(date(pr_merged_date))+1 DAY) as time,\n  avg(TIMESTAMPDIFF(Minute,pr_created_date,pr_merged_date)/1440) as 'PR Review Time'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "From PR merged to changes deployed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no deploy_time to make sure cycle_time equals the sum of the four sub-metrics\n\t\tcoalesce(prm.pr_deploy_time/1440,0) as deploy_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(deploy_time) as 'PR Deploy Time(days)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}